### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by profesionalleet1337** [ishan-saha/SmishingTool#1]
Dude, i need help with setting up . Do u have any form of contact ? Discord, facebook ? Somewhere, i could ciontact you ?

**Comment by ishan-saha** [comment]
what is the issue youre facing?

**Comment by profesionalleet1337** [comment]
@ishan-saha I though the project is closed .. ( So long time - no reply from your side ) . 
Could u give me your discord, or some contact form, where i could communicate with you ?

**Comment by ishan-saha** [comment]
nukester#7182
